import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTableModule } from '@angular/material/table';
import { MatTabsModule } from '@angular/material/tabs';
import { MatTooltipModule } from '@angular/material/tooltip';
import { ApiService } from '../../../core/services/api.service';

@Component({
  selector:'app-fap', standalone:true,
  imports:[CommonModule,ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSelectModule,MatSnackBarModule,MatTableModule,MatTabsModule,MatTooltipModule],
  template:`
  <div class="page-container fade-in-up">
    <div class="page-header"><div><h1>FAP</h1><p>Administración de porcentajes y valores mensuales</p></div></div>
    <mat-tab-group animationDuration="200ms">
      <mat-tab label="Matriz FAP"><div class="tab-content">
        <div class="toolbar card">
          <mat-form-field appearance="outline"><mat-label>Estructura / tipo de obra</mat-label><mat-select [value]="estructuraId()" (selectionChange)="seleccionarEstructura($event.value)">@for(e of estructuras();track e.id){<mat-option [value]="e.id">{{e.nombre}}</mat-option>}</mat-select></mat-form-field>
          <button mat-stroked-button (click)="editarEstructura()"><mat-icon>edit</mat-icon> Editar estructura</button>
          <button mat-stroked-button (click)="nuevaEstructura()"><mat-icon>add</mat-icon> Estructura</button>
          <span class="spacer"></span>
          <input #matrizFile hidden type="file" accept=".xlsx,.xlsm" (change)="importar($event,'matriz')"><button mat-stroked-button (click)="matrizFile.click()"><mat-icon>upload_file</mat-icon> Importar matriz</button>
          <button mat-raised-button color="primary" (click)="guardarMatriz()"><mat-icon>save</mat-icon> Guardar porcentajes</button>
        </div>
        <div class="matrix-info"><span>{{items().length}} ítems</span><span>Total estructura: <strong [class.bad]="Math.abs(totalPorcentaje()-1)>.0001">{{totalPorcentaje()|percent:'1.0-2'}}</strong></span><button mat-button color="primary" (click)="nuevoItem()"><mat-icon>add</mat-icon> Nuevo ítem</button></div>
        <div class="card table-wrap"><table mat-table [dataSource]="items()">
          <ng-container matColumnDef="item"><th mat-header-cell *matHeaderCellDef>Ítem</th><td mat-cell *matCellDef="let i"><strong>{{i.nombre}}</strong><small>{{i.indiceIndec||'Sin referencia INDEC'}}</small></td></ng-container>
          <ng-container matColumnDef="porcentaje"><th mat-header-cell *matHeaderCellDef>Porcentaje</th><td mat-cell *matCellDef="let i"><div class="percent-input"><input type="number" min="0" max="100" step="0.01" [value]="porcentaje(i.id)*100" (input)="cambiarPorcentaje(i.id,$event)"><span>%</span></div></td></ng-container>
          <ng-container matColumnDef="acciones"><th mat-header-cell *matHeaderCellDef></th><td mat-cell *matCellDef="let i" class="actions"><button mat-icon-button (click)="editarItem(i)" matTooltip="Editar"><mat-icon>edit</mat-icon></button><button mat-icon-button color="warn" (click)="eliminarItem(i)" matTooltip="Eliminar"><mat-icon>delete</mat-icon></button></td></ng-container>
          <tr mat-header-row *matHeaderRowDef="['item','porcentaje','acciones']"></tr><tr mat-row *matRowDef="let row;columns:['item','porcentaje','acciones']"></tr>
        </table></div>
      </div></mat-tab>

      <mat-tab label="Valores mensuales"><div class="tab-content">
        <div class="toolbar card"><button mat-raised-button color="primary" (click)="nuevoPeriodo()"><mat-icon>add</mat-icon> Cargar mes</button><span class="spacer"></span><input #mensualFile hidden type="file" accept=".xlsx,.xlsm" (change)="importar($event,'mensual')"><button mat-stroked-button (click)="mensualFile.click()"><mat-icon>upload_file</mat-icon> Importar historial mensual</button></div>
        <div class="period-grid">@for(p of periodos();track p.id){<div class="period-card card"><div class="period-icon"><mat-icon>calendar_month</mat-icon></div><div class="period-info"><h3>{{nombrePeriodo(p.periodo)}}</h3><p>{{p.valores.length}} valores cargados</p></div><button mat-icon-button (click)="editarPeriodo(p)" matTooltip="Editar"><mat-icon>edit</mat-icon></button><button mat-icon-button color="warn" (click)="eliminarPeriodo(p)" matTooltip="Eliminar"><mat-icon>delete</mat-icon></button></div>}@empty{<div class="empty">No hay períodos cargados</div>}</div>
      </div></mat-tab>
    </mat-tab-group>
  </div>

  @if(itemModal()){<div class="overlay"><div class="dialog small"><div class="dialog-head"><h2>{{itemEditando()?.id?'Editar':'Nuevo'}} ítem</h2><button mat-icon-button (click)="itemModal.set(false)"><mat-icon>close</mat-icon></button></div><form [formGroup]="itemForm" (ngSubmit)="guardarItem()"><mat-form-field appearance="outline"><mat-label>Nombre</mat-label><input matInput formControlName="nombre"></mat-form-field><mat-form-field appearance="outline"><mat-label>Índice / referencia INDEC</mat-label><textarea matInput rows="5" formControlName="indiceIndec"></textarea></mat-form-field><div class="dialog-actions"><button mat-stroked-button type="button" (click)="itemModal.set(false)">Cancelar</button><button mat-raised-button color="primary">Guardar</button></div></form></div></div>}
  @if(periodoModal()){<div class="overlay"><div class="dialog"><div class="dialog-head"><div><h2>{{periodoEditandoId()?'Editar':'Cargar'}} valores mensuales</h2><p>Ingresá el valor correspondiente a cada ítem</p></div><button mat-icon-button (click)="periodoModal.set(false)"><mat-icon>close</mat-icon></button></div><form [formGroup]="periodoForm" (ngSubmit)="guardarPeriodo()"><div class="period-selector"><mat-form-field appearance="outline"><mat-label>Mes</mat-label><mat-select formControlName="mes">@for(m of meses;track m.numero){<mat-option [value]="m.numero">{{m.nombre}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Año</mat-label><input matInput type="number" min="2000" max="2100" formControlName="anio"></mat-form-field></div><div formArrayName="valores" class="value-grid">@for(g of valores.controls;track $index){<div class="value-row" [formGroupName]="$index"><label>{{items()[$index]?.nombre}}</label><input type="number" min="0" step="0.0001" formControlName="valor"></div>}</div><div class="dialog-actions"><button mat-stroked-button type="button" (click)="periodoModal.set(false)">Cancelar</button><button mat-raised-button color="primary">Guardar mes</button></div></form></div></div>}
  `,
  styles:[`
    .page-header{margin-bottom:18px}h1{font-size:26px;font-weight:800}p{font-size:13px;color:var(--text-secondary)}.tab-content{padding:20px 0}.toolbar{padding:14px;display:flex;align-items:center;gap:10px;flex-wrap:wrap}.toolbar mat-form-field{width:min(430px,100%);margin-bottom:-20px}.spacer{flex:1}.matrix-info{display:flex;align-items:center;gap:20px;padding:16px 4px;color:var(--text-secondary)}.matrix-info button{margin-left:auto}.matrix-info strong{color:var(--color-accent-dark)}.matrix-info strong.bad{color:#c62828}.table-wrap{overflow:hidden}table{width:100%}td strong,td small{display:block}td small{max-width:700px;color:var(--text-secondary);margin-top:3px}.percent-input{display:flex;align-items:center;gap:6px}.percent-input input{width:110px;padding:9px;border:1px solid var(--border-color);border-radius:7px;text-align:right}.actions{text-align:right}.period-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:14px;margin-top:16px}.period-card{display:flex;align-items:center;padding:16px;gap:12px}.period-icon{width:42px;height:42px;border-radius:10px;background:#e8f6ee;display:flex;align-items:center;justify-content:center;color:var(--color-accent-dark)}.period-info{flex:1}.period-info h3{text-transform:capitalize;font-size:15px}.empty{grid-column:1/-1;padding:50px;text-align:center;color:var(--text-secondary)}
    .overlay{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:1000;display:flex;align-items:center;justify-content:center;padding:16px}.dialog{width:min(850px,100%);max-height:92vh;overflow:auto;background:white;border-radius:15px;box-shadow:var(--shadow-lg)}.dialog.small{width:min(520px,100%)}.dialog-head{display:flex;align-items:center;justify-content:space-between;padding:20px 24px;border-bottom:1px solid var(--border-color)}.dialog form{padding:22px}.dialog.small mat-form-field{width:100%}.period-selector{display:grid;grid-template-columns:1fr 160px;gap:12px;max-width:480px}.dialog-actions{display:flex;justify-content:flex-end;gap:10px;padding-top:16px;margin-top:14px;border-top:1px solid var(--border-color)}.value-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 18px}.value-row{display:grid;grid-template-columns:1fr 145px;align-items:center;gap:8px;padding:7px;border-bottom:1px solid #eee}.value-row label{font-size:13px}.value-row input{padding:9px;border:1px solid var(--border-color);border-radius:7px;text-align:right}@media(max-width:700px){.value-grid{grid-template-columns:1fr}.toolbar .spacer{display:none}.period-selector{grid-template-columns:1fr}}
  `]
})
export class FapComponent implements OnInit {
  private api=inject(ApiService);private fb=inject(FormBuilder);private snack=inject(MatSnackBar);Math=Math;
  items=signal<any[]>([]);estructuras=signal<any[]>([]);periodos=signal<any[]>([]);estructuraId=signal<number|null>(null);matriz=new Map<number,number>();
  itemModal=signal(false);itemEditando=signal<any|null>(null);periodoModal=signal(false);periodoEditandoId=signal<number|null>(null);
  meses=[{numero:1,nombre:'Enero'},{numero:2,nombre:'Febrero'},{numero:3,nombre:'Marzo'},{numero:4,nombre:'Abril'},{numero:5,nombre:'Mayo'},{numero:6,nombre:'Junio'},{numero:7,nombre:'Julio'},{numero:8,nombre:'Agosto'},{numero:9,nombre:'Septiembre'},{numero:10,nombre:'Octubre'},{numero:11,nombre:'Noviembre'},{numero:12,nombre:'Diciembre'}];
  itemForm=this.fb.group({nombre:['',Validators.required],indiceIndec:['']});
  periodoForm=this.fb.group({mes:[null as number|null,Validators.required],anio:[new Date().getFullYear(),[Validators.required,Validators.min(2000),Validators.max(2100)]],valores:this.fb.array([])});get valores(){return this.periodoForm.controls.valores as FormArray;}
  ngOnInit(){this.cargarTodo();}
  cargarTodo(){this.api.get<any>('fap/catalogo').subscribe({next:r=>{this.items.set(r.items);this.estructuras.set(r.estructuras);if(!this.estructuraId()&&r.estructuras.length)this.seleccionarEstructura(r.estructuras[0].id)}});this.api.get<any[]>('fap/periodos').subscribe({next:r=>this.periodos.set(r)});}
  seleccionarEstructura(id:number){this.estructuraId.set(id);this.matriz.clear();for(const item of this.items()){const p=item.porcentajes?.find((x:any)=>x.estructuraId===id);this.matriz.set(item.id,p?+p.porcentaje:0);}}
  porcentaje(id:number){return this.matriz.get(id)??0;}cambiarPorcentaje(id:number,event:Event){this.matriz.set(id,(+(event.target as HTMLInputElement).value||0)/100);}totalPorcentaje(){return [...this.matriz.values()].reduce((a,b)=>a+b,0);}
  guardarMatriz(){const estructuraId=this.estructuraId();if(!estructuraId)return;this.api.put('fap/matriz',{celdas:this.items().map(i=>({itemId:i.id,estructuraId,porcentaje:this.porcentaje(i.id)}))}).subscribe({next:()=>{this.ok('Porcentajes guardados');this.cargarTodo()},error:e=>this.error(e)});}
  nuevoItem(){this.itemEditando.set(null);this.itemForm.reset({nombre:'',indiceIndec:''});this.itemModal.set(true);}editarItem(i:any){this.itemEditando.set(i);this.itemForm.patchValue(i);this.itemModal.set(true);}guardarItem(){if(this.itemForm.invalid)return;const i=this.itemEditando();const op=i?this.api.put(`fap/items/${i.id}`,this.itemForm.value):this.api.post('fap/items',this.itemForm.value);op.subscribe({next:()=>{this.itemModal.set(false);this.cargarTodo();this.ok('Ítem guardado')},error:e=>this.error(e)});}eliminarItem(i:any){if(!confirm(`¿Eliminar ${i.nombre}?`))return;this.api.delete(`fap/items/${i.id}`).subscribe({next:()=>this.cargarTodo(),error:e=>this.error(e)});}
  nuevaEstructura(){const nombre=prompt('Nombre de la nueva estructura');if(!nombre)return;this.api.post('fap/estructuras',{nombre}).subscribe({next:()=>{this.cargarTodo();this.ok('Estructura creada')},error:e=>this.error(e)});}editarEstructura(){const e=this.estructuras().find(x=>x.id===this.estructuraId());if(!e)return;const nombre=prompt('Nombre de la estructura',e.nombre);if(!nombre)return;this.api.put(`fap/estructuras/${e.id}`,{nombre}).subscribe({next:()=>this.cargarTodo(),error:x=>this.error(x)});}
  nuevoPeriodo(){this.periodoEditandoId.set(null);this.periodoForm.patchValue({mes:null,anio:new Date().getFullYear()});this.prepararValores([]);this.periodoModal.set(true);}editarPeriodo(p:any){const partes=this.partesPeriodo(p.periodo);this.periodoEditandoId.set(p.id);this.periodoForm.patchValue({mes:partes.mes,anio:partes.anio});this.prepararValores(p.valores);this.periodoModal.set(true);}prepararValores(actuales:any[]){this.valores.clear();for(const item of this.items()){const actual=actuales.find(x=>x.itemId===item.id);this.valores.push(this.fb.group({itemId:[item.id],valor:[actual?+actual.valor:null,[Validators.required,Validators.min(0)]]}));}}
  guardarPeriodo(){if(this.periodoForm.invalid){this.periodoForm.markAllAsTouched();return}const raw=this.periodoForm.getRawValue(),mes=String(raw.mes).padStart(2,'0'),payload={periodo:`${raw.anio}-${mes}-01`,valores:raw.valores};const id=this.periodoEditandoId();const op=id?this.api.put(`fap/periodos/${id}`,payload):this.api.post('fap/periodos',payload);op.subscribe({next:()=>{this.periodoModal.set(false);this.cargarTodo();this.ok('Mes guardado')},error:e=>this.error(e)});}eliminarPeriodo(p:any){if(!confirm(`¿Eliminar ${this.nombrePeriodo(p.periodo)}?`))return;this.api.delete(`fap/periodos/${p.id}`).subscribe({next:()=>this.cargarTodo(),error:e=>this.error(e)});}
  nombrePeriodo(periodo:string){const {mes,anio}=this.partesPeriodo(periodo);return `${this.meses[mes-1]?.nombre??''} ${anio}`;}
  private partesPeriodo(periodo:string){const match=String(periodo).match(/^(\d{4})-(\d{2})/);return {anio:match?Number(match[1]):0,mes:match?Number(match[2]):0};}
  importar(event:Event,tipo:'matriz'|'mensual'){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;const data=new FormData();data.append('file',file);this.api.post<any>(`fap/importar-${tipo}`,data).subscribe({next:r=>{this.ok(tipo==='matriz'?`${r.items} ítems importados`:`${r.periodos} meses importados`);this.cargarTodo();input.value=''},error:e=>this.error(e)});}
  private ok(m:string){this.snack.open(m,'',{duration:3000,panelClass:'snack-success'});}private error(e:any){this.snack.open(e?.error?.message??'No se pudo completar la operación','Cerrar',{duration:4500,panelClass:'snack-error'});}
}
